import type { GameEvent } from '../engine'

// Obstacles universels d'une course contre la montre, réutilisables par les chapitres.
// Aucun ne donne d'objectif : ce sont des fillers.

// ── Rue, transport, social : fonctionnent dans n'importe quel chapitre. ──
export const STREET: GameEvent[] = [
  {
    id: 'voisin',
    sprite: 'voisin',
    decor: 'rue',
    prop: 'tondeuse',
    title: 'Le voisin du dessous',
    text: "À peine sorti, le voisin t'alpague. Il a des choses à dire sur sa nouvelle tondeuse. Beaucoup de choses.",
    choices: [
      { label: 'Écouter poliment', effect: { temps: -16, moral: 4 }, result: "Vingt minutes sur l'autonomie de batterie. Du temps perdu, un allié gagné." },
      { label: 'Couper court sèchement', effect: { temps: -3, moral: -8 }, result: 'Tu files. Il reste planté là, vexé.' },
      { label: 'Mimer un appel urgent', effect: { temps: -6, energie: -2 }, result: "Tu colles le téléphone à ton oreille. Il n'est pas dupe, mais ça marche." },
    ],
  },
  {
    id: 'chien',
    sprite: 'chien',
    decor: 'rue',
    prop: 'os',
    title: 'Le chien sans laisse',
    text: 'Un gros chien débonnaire te barre le trottoir. Il te fixe, la queue remuante. Son maître est introuvable.',
    choices: [
      { label: 'Le contourner large', effect: { temps: -4, energie: -3 }, result: 'Grand détour par la chaussée. Prudence avant tout.' },
      { label: 'Le caresser', effect: { temps: -5, moral: 10, energie: -2 }, result: 'Boule de poils adorable. Trente secondes de bonheur pur.' },
      { label: 'Passer en vitesse', effect: { temps: -1, energie: -8, moral: -4 }, result: 'Il te suit en jappant sur dix mètres. Frayeur inutile.' },
    ],
  },
  {
    id: 'pluie',
    sprite: 'papa',
    decor: 'rue',
    prop: 'parapluie',
    title: "L'averse soudaine",
    text: 'Le ciel lâche tout sans prévenir. Tu es à découvert, sans parapluie, évidemment.',
    choices: [
      { label: "S'abriter sous un porche", effect: { temps: -12, moral: -3 }, result: 'Tu attends que ça passe, dégoulinant à moitié. Le temps file.' },
      { label: 'Courir sous la pluie', effect: { temps: -3, energie: -10, moral: -6 }, result: 'Trempé jusqu’aux chaussettes. Rapide, mais misérable.' },
      { label: 'Appeler un taxi', effect: { temps: -5, argent: -10, energie: 4 }, result: 'Cinq minutes au sec. Le portefeuille morfle, le moral tient.' },
    ],
  },
  {
    id: 'ex',
    sprite: 'ex',
    decor: 'rue',
    prop: 'lunettes',
    title: 'La rencontre gênante',
    text: 'En plein trottoir, ton ex. Impeccable, comme toujours. Toi, en jogging, en pleine mission express.',
    choices: [
      { label: 'Discuter cinq minutes', effect: { temps: -10, moral: -4 }, result: 'Conversation polie et glaciale. Légère envie de disparaître.' },
      { label: 'Faire semblant de rien', effect: { temps: -2, moral: -8 }, result: "Tu fixes ton téléphone. Elle t'a vu te cacher. C'est pire." },
      { label: 'Saluer et filer', effect: { temps: -4, moral: 8 }, result: 'Bonjour franc, sourire, et tu continues. Classe maîtrisée.' },
    ],
  },
  {
    id: 'bar',
    sprite: 'barman',
    decor: 'bar',
    prop: 'biere',
    title: 'La terrasse qui appelle',
    text: 'Un bar ensoleillé, des copains qui te font signe. Une bière fraîche scintille. La mission peut-elle attendre ?',
    choices: [
      { label: 'Juste une, vite fait', effect: { temps: -14, energie: 6, moral: 12 }, result: 'Une demi, deux blagues. Mais le temps, lui, ne plaisante pas.' },
      { label: 'Résister héroïquement', effect: { temps: -1, moral: -9, energie: -2 }, result: 'Tu déclines. Le devoir avant le houblon.' },
      { label: 'Trinquer et repartir', effect: { temps: -6, moral: 6 }, result: 'Un verre d’eau, une accolade, et tu repars. Le bon compromis.' },
    ],
  },
  {
    id: 'sdf',
    sprite: 'sdf',
    decor: 'rue',
    prop: 'piece',
    title: 'La pièce demandée',
    text: 'Un homme assis sur le trottoir te demande une pièce, le sourire fatigué.',
    choices: [
      { label: 'Donner une pièce', effect: { temps: -2, argent: -2, moral: 9 }, result: 'Un merci sincère. Ça ne coûte rien et ça réchauffe.' },
      { label: 'Sourire et passer', effect: { temps: -1 }, result: 'Tu salues d’un signe et continues.' },
    ],
  },
  {
    id: 'raccourci',
    sprite: 'papa',
    decor: 'parc',
    prop: 'horloge',
    title: 'Le raccourci par le parc',
    text: 'Un sentier coupe par le parc. Plus court, mais boueux après la dernière pluie.',
    choices: [
      { label: 'Prendre le raccourci', effect: { temps: 8, energie: -6, moral: -3 }, result: 'Tu gagnes du temps mais finis crotté jusqu’aux genoux.' },
      { label: 'Rester sur le trottoir', effect: { temps: -6, energie: 2 }, result: 'Itinéraire propre et sûr, un peu plus long.' },
    ],
  },
  {
    id: 'panne_velo',
    sprite: 'papa',
    decor: 'rue',
    prop: 'velo',
    title: 'Le vélo en libre service',
    text: 'Une borne de vélos partagés. Tu pourrais gagner un temps fou, si l’appli daigne fonctionner.',
    choices: [
      { label: 'Pédaler comme un fou', effect: { temps: 12, energie: -9, argent: -3 }, result: 'Cheveux au vent, jambes en feu. Gain de temps spectaculaire.' },
      { label: 'Renoncer, l’appli bug', effect: { temps: -4, moral: -3 }, result: 'Trois QR codes, zéro vélo. Tu repars à pied, agacé.' },
    ],
  },
  {
    id: 'gouter',
    sprite: 'papa',
    decor: 'boulangerie',
    prop: 'painchoco',
    title: 'Le creux de 11h',
    text: 'Ton ventre gargouille. Une boulangerie ouverte embaume tout le trottoir.',
    choices: [
      { label: 'Un pain au chocolat', effect: { temps: -5, argent: -2, energie: 9, moral: 5 }, result: 'Réconfort instantané. Tu repars rechargé.' },
      { label: 'Serrer les dents', effect: { temps: -1, energie: -5, moral: -3 }, result: 'Tu résistes. L’estomac proteste.' },
    ],
  },
  {
    id: 'arret_bus',
    sprite: 'mamie',
    decor: 'arret_bus',
    prop: 'horloge',
    title: "L'arrêt de bus",
    text: 'Un bus pourrait te rapprocher. L’horaire, lui, reste un mystère insondable.',
    choices: [
      { label: 'Attendre le bus', effect: { temps: -10, energie: 6 }, result: 'Il finit par arriver. Assis, au repos, mais le temps a coulé.' },
      { label: 'Continuer à pied', effect: { temps: -5, energie: -5 }, result: 'Tu ne fais pas confiance aux bus. Tu marches.' },
    ],
  },
  {
    id: 'cycliste',
    sprite: 'cycliste',
    decor: 'rue',
    prop: 'feu',
    title: 'Le cycliste pressé',
    text: 'Un livreur à vélo grille le feu et te frôle au passage piéton. Frayeur et sonnette agressive.',
    choices: [
      { label: 'Respirer un grand coup', effect: { temps: -2, moral: 3 }, result: 'Tu laisses passer l’adrénaline. Pas de quoi gâcher ta journée.' },
      { label: 'Crier ton mécontentement', effect: { temps: -3, energie: -4, moral: -3 }, result: 'Il est déjà loin. Tu cries dans le vide.' },
    ],
  },
  {
    id: 'cafe_pause',
    sprite: 'barman',
    decor: 'boulangerie',
    prop: 'cafe',
    title: 'Le comptoir du coin',
    text: 'Un petit café de quartier. Un expresso te remettrait peut-être d’aplomb.',
    choices: [
      { label: 'Expresso au comptoir', effect: { temps: -6, argent: -2, energie: 11 }, result: 'Serré, brûlant, parfait. Coup de fouet immédiat.' },
      { label: 'Passer ton chemin', effect: { temps: -1, energie: -3 }, result: 'Pas le temps. Tu continues, un peu raplapla.' },
    ],
  },
  {
    id: 'belle_mere',
    sprite: 'mamie',
    decor: 'rue',
    prop: 'telephone',
    title: "L'appel de la belle-mère",
    text: "Numéro masqué. C'est ta belle-mère. Elle a appris pour la mission et veut absolument te conseiller.",
    choices: [
      { label: 'Acquiescer poliment', effect: { temps: -9, moral: -3 }, result: 'Tu dis oui à tout pendant cinq minutes. Paix sociale préservée.' },
      { label: 'Écourter fermement', effect: { temps: -3, moral: -6 }, result: '"Je gère, merci." Silence pincé. Tu paieras ça au prochain repas.' },
    ],
  },
  {
    id: 'flaque',
    sprite: 'cycliste',
    decor: 'rue',
    prop: 'nuage',
    title: "L'arroseur arrosé",
    text: 'Une voiture file dans une flaque énorme juste à côté de toi. Le mur d’eau arrive au ralenti.',
    choices: [
      { label: 'Bondir en arrière', effect: { temps: -4, energie: -6 }, result: 'Réflexe de félin. Pantalon sauvé, effort brusque.' },
      { label: 'Encaisser, fataliste', effect: { temps: -1, moral: -8 }, result: 'Douche froide intégrale. Le destin se moque de toi.' },
    ],
  },
  {
    id: 'sondage',
    sprite: 'collegue',
    decor: 'allee',
    prop: 'liste',
    title: 'Le sondeur de rue',
    text: 'Un jeune homme avec une tablette te bloque : "Deux minutes pour un questionnaire ?"',
    choices: [
      { label: 'Répondre vite fait', effect: { temps: -8, moral: 2 }, result: 'Quinze questions. Tu mens à toutes, ça va plus vite.' },
      { label: 'Esquiver poliment', effect: { temps: -2 }, result: '"Désolé, urgence." Argument imparable.' },
    ],
  },
  {
    id: 'chat_perdu',
    sprite: 'papa',
    decor: 'ruelle',
    prop: 'coeur',
    title: 'Le chat de la ruelle',
    text: 'Un chat tigré te suit en miaulant. Il a l’air de te connaître. Toi, pas du tout.',
    choices: [
      { label: 'Le caresser un instant', effect: { temps: -5, moral: 11 }, result: 'Ronronnement immédiat. Parenthèse de douceur.' },
      { label: 'Continuer, indifférent', effect: { temps: -1, energie: 2 }, result: 'Le chat te juge, puis se désintéresse de toi.' },
    ],
  },
  {
    id: 'travaux',
    sprite: 'vigile',
    decor: 'rue',
    prop: 'feu',
    title: 'Le trottoir éventré',
    text: 'Des travaux barrent tout le trottoir. Un ouvrier te fait signe de contourner par on ne sait où.',
    choices: [
      { label: 'Contourner sagement', effect: { temps: -8, energie: -2 }, result: 'Détour balisé par des plots oranges. Plus long, mais sûr.' },
      { label: 'Slalomer entre les engins', effect: { temps: -3, moral: -2 }, result: 'Tu te faufiles sous le regard noir du chef de chantier.' },
    ],
  },
  {
    id: 'livreur_colis',
    sprite: 'collegue',
    decor: 'rue',
    prop: 'sac',
    title: 'Le diable du livreur',
    text: 'Un livreur empile dix cartons sur un diable en travers du passage, sans se presser le moins du monde.',
    choices: [
      { label: 'Attendre poliment', effect: { temps: -3 }, result: 'Tu patientes le temps qu’il dégage. Civisme récompensé par de la lenteur.' },
      { label: 'L’aider à décharger', effect: { temps: -9, energie: -4, moral: 7 }, result: 'Un coup de main et la voie se libère. Bonne action, mauvais timing.' },
    ],
  },
  {
    id: 'vieux_copain',
    sprite: 'voisin',
    decor: 'rue',
    prop: 'coeur',
    title: "Le copain d'enfance",
    text: 'Un visage du passé surgit : "Non mais je rêve, c’est toi ?!" Vingt ans qu’on ne s’est pas vus.',
    choices: [
      { label: 'Un vrai moment, vite fait', effect: { temps: -11, moral: 9 }, result: 'Souvenirs, éclats de rire, numéros échangés. Chaleureux mais coûteux.' },
      { label: 'Promettre de se rappeler', effect: { temps: -3, moral: -2 }, result: '"Je t’appelle, on se fait ça !" Tu files, vaguement nostalgique.' },
    ],
  },
  {
    id: 'gravillon',
    sprite: 'papa',
    decor: 'rue',
    title: 'Le caillou dans la chaussure',
    text: 'Un gravillon traître s’est invité sous ton pied et te martyrise à chaque pas.',
    choices: [
      { label: 'S’arrêter pour l’enlever', effect: { temps: -4, energie: 3 }, result: 'Trente secondes assis, problème réglé. Soulagement immédiat.' },
      { label: 'Serrer les dents et avancer', effect: { temps: -1, energie: -5, moral: -3 }, result: 'Tu boites stoïquement. Le caillou gagne du terrain dans ton moral.' },
    ],
  },
  {
    id: 'manif',
    sprite: 'ado',
    decor: 'rue',
    prop: 'journal',
    title: 'Le cortège imprévu',
    text: 'Une manifestation bon enfant remonte l’avenue avec banderoles et tambours, et coupe ta route.',
    choices: [
      { label: 'Attendre qu’il passe', effect: { temps: -7, moral: 2 }, result: 'Tu patientes au son des slogans. Sympathique, mais immobile.' },
      { label: 'Remonter à contre-courant', effect: { temps: -3, energie: -3 }, result: 'Tu fends la foule à l’envers, bousculé mais en mouvement.' },
    ],
  },
  {
    id: 'vendeur_rue',
    sprite: 'barman',
    decor: 'rue',
    prop: 'journal',
    title: 'Le vendeur à la sauvette',
    text: 'Un vendeur déploie sa nappe de gadgets pile devant toi et entame son boniment irrésistible.',
    choices: [
      { label: 'Décliner et contourner', effect: { temps: -3 }, result: '"Non merci, vraiment." Tu l’esquives sans ralentir.' },
      { label: 'Craquer pour un truc inutile', effect: { temps: -6, argent: -5, moral: 4 }, result: 'Te voilà avec un porte-clés lumineux dont tu n’avais aucun besoin.' },
    ],
  },
]

// ── Spécifique magasins (chapitres en grande surface). ──
export const STORE: GameEvent[] = [
  {
    id: 'monnaie',
    sprite: 'caissier',
    decor: 'caisse',
    prop: 'carte',
    title: 'Le terminal en rade',
    text: 'À la caisse, le lecteur de carte refuse ton paiement : "Réseau indisponible, espèces uniquement."',
    choices: [
      { label: 'Payer en liquide', effect: { temps: -4, moral: -2 }, result: 'Tu comptes tes pièces centime par centime. La file soupire derrière toi.' },
      { label: 'Réessayer la carte trois fois', effect: { temps: -9, moral: -4 }, result: 'Refus, refus, refus. Au quatrième essai, ça passe. Sueurs froides.' },
    ],
  },
  {
    id: 'prix_errone',
    sprite: 'caissier',
    decor: 'caisse',
    prop: 'ticket',
    title: 'Le prix qui ne colle pas',
    text: 'En caisse, l’article sonne deux euros de plus que l’étiquette du rayon. Le caissier hausse les épaules.',
    choices: [
      { label: 'Réclamer le bon prix', effect: { temps: -9, argent: 2, moral: 3 }, result: 'Vérification au rayon, prix corrigé. Tu avais raison, et tu économises.' },
      { label: 'Laisser couler', effect: { temps: -2, argent: -2 }, result: 'Pas le temps de chipoter pour deux euros. Tu paies et tu files.' },
    ],
  },
  {
    id: 'rayon_deplace',
    sprite: 'vigile',
    decor: 'supermarche',
    prop: 'panier',
    title: 'Le magasin réagencé',
    text: 'Tout a été déplacé depuis la dernière fois. Ce que tu cherches a migré dans une allée inconnue.',
    choices: [
      { label: 'Demander à un employé', effect: { temps: -4, moral: 2 }, result: 'Il te pointe la bonne allée du doigt. Gain de temps net.' },
      { label: 'Chercher seul, têtu', effect: { temps: -11, energie: -4, moral: -3 }, result: 'Tu écumes six allées avant de tomber dessus. Fierté coûteuse.' },
    ],
  },
  {
    id: 'caisse_queue',
    sprite: 'mamie',
    decor: 'caisse',
    prop: 'ticket',
    title: 'La file de la caisse',
    text: 'Une seule caisse ouverte. Devant toi, une dame règle en pièces de un centime.',
    choices: [
      { label: 'Patienter en zen', effect: { temps: -15, moral: 3 }, result: 'Tu respires. Étrangement apaisant.' },
      { label: 'Caisse automatique', effect: { temps: -9, energie: -5, moral: -6 }, result: 'Article non reconnu. Veuillez attendre un agent. Classique.' },
      { label: 'Lâcher la file', effect: { temps: -2, moral: -7 }, result: 'Tu abandonnes la queue, frustré.' },
    ],
  },
  {
    id: 'vigile',
    sprite: 'vigile',
    decor: 'supermarche',
    prop: 'etoile',
    title: 'Le vigile soupçonneux',
    text: 'Tu tournes les mains vides depuis dix minutes. Le vigile te suit du regard.',
    choices: [
      { label: 'Lui expliquer', effect: { temps: -6, moral: 4 }, result: 'Il comprend, te pointe même le bon rayon. Solidarité.' },
      { label: 'L’ignorer', effect: { temps: -3, moral: -5, energie: -2 }, result: 'Tu joues l’indifférent sous l’oeil méfiant.' },
    ],
  },
  {
    id: 'caddie',
    sprite: 'papa',
    decor: 'parking',
    prop: 'caddie',
    title: 'Le caddie à pièce',
    text: 'Les caddies sont enchaînés. Il faut une pièce de un euro. Tu fouilles tes poches.',
    choices: [
      { label: 'Café pour la monnaie', effect: { temps: -7, argent: -2, energie: 5 }, result: 'Un café pour faire l’appoint. Caddie débloqué, et toi aussi.' },
      { label: 'Panier à la main', effect: { temps: -2, energie: -7 }, result: 'Pas de caddie, tu portes tout à bras. Le dos s’en souviendra.' },
    ],
  },
  {
    id: 'promo',
    sprite: 'caissiere',
    decor: 'allee',
    prop: 'promo',
    title: 'La tête de gondole',
    text: 'Une promo agressive sur des trucs inutiles. Mais -50%, quand même.',
    choices: [
      { label: 'Résister', effect: { temps: -2, moral: 5 }, result: 'Tu passes ton chemin, fier de ta discipline.' },
      { label: 'Craquer un peu', effect: { temps: -7, argent: -8, moral: 6 }, result: 'Un gadget inutile, une petite joie coupable.' },
    ],
  },
  {
    id: 'degustation',
    sprite: 'caissiere',
    decor: 'supermarche',
    prop: 'chips',
    title: 'Le stand dégustation',
    text: 'Une hôtesse propose des cubes de fromage gratuits sur des piques. Ton estomac répond avant toi.',
    choices: [
      { label: 'Goûter discrètement', effect: { temps: -4, energie: 7, moral: 4 }, result: 'Trois cubes, mine de rien. Énergie regonflée.' },
      { label: 'Décliner dignement', effect: { temps: -1, moral: 2 }, result: 'Tu remercies et passes, le ventre vide mais la tête haute.' },
    ],
  },
  {
    id: 'enfant_perdu',
    sprite: 'enfant',
    decor: 'allee',
    prop: 'doudou',
    title: "L'enfant perdu",
    text: 'Un petit pleure au milieu de l’allée, il a perdu ses parents. Personne ne s’arrête.',
    choices: [
      { label: 'L’aider à retrouver sa mère', effect: { temps: -12, moral: 14 }, result: 'Annonce au micro, retrouvailles. Du temps perdu, de l’humanité gagnée.' },
      { label: 'Prévenir un employé', effect: { temps: -4, moral: 2 }, result: 'Tu signales l’enfant et poursuis, la conscience tranquille.' },
    ],
  },
]

// ── Transports en commun. ──
export const TRANSPORT: GameEvent[] = [
  {
    id: 'metro_panne',
    sprite: 'mamie',
    decor: 'arret_bus',
    prop: 'horloge',
    title: 'Le métro à quai',
    text: 'Annonce grésillante : "Trafic interrompu sur la ligne." La foule hésite sur le quai.',
    choices: [
      { label: 'Attendre la reprise', effect: { temps: -12, energie: 5 }, result: 'Le trafic reprend, mais tu as perdu un temps fou.' },
      { label: 'Remonter et courir', effect: { temps: -6, energie: -9 }, result: 'Tu remontes à la surface au pas de course. Les mollets chauffent.' },
    ],
  },
  {
    id: 'bus_bonde',
    sprite: 'collegue',
    decor: 'arret_bus',
    prop: 'sac',
    title: 'Le bus bondé',
    text: 'Le bus arrive plein à craquer. Le chauffeur hésite à ouvrir les portes.',
    choices: [
      { label: 'Te tasser à l’intérieur', effect: { temps: -5, energie: -7, moral: -3 }, result: 'Sardine humaine, coude dans les côtes. Mais tu avances.' },
      { label: 'Attendre le suivant', effect: { temps: -11, energie: 3 }, result: 'Tu laisses passer. Le prochain est dans dix longues minutes.' },
    ],
  },
  {
    id: 'controleur',
    sprite: 'vigile',
    decor: 'arret_bus',
    prop: 'ticket',
    title: 'Le contrôle surprise',
    text: 'Contrôleurs à la sortie. Tu fouilles tes poches à la recherche de ton titre de transport.',
    choices: [
      { label: 'Montrer ton ticket', effect: { temps: -5 }, result: 'Tout est en règle. Tu passes, soulagé.' },
      { label: 'Le chercher partout', effect: { temps: -9, moral: -5 }, result: 'Tu le retrouves froissé au fond. Sueurs froides pour rien.' },
    ],
  },
  {
    id: 'correspondance',
    sprite: 'papa',
    decor: 'arret_bus',
    prop: 'horloge',
    title: 'La correspondance ratée',
    text: 'Tu sprintes dans le couloir pour ta correspondance. Les portes commencent à sonner.',
    choices: [
      { label: 'Sauter dans la rame', effect: { temps: 6, energie: -8 }, result: 'Tu te glisses entre les portes au dernier centième. Gagné !' },
      { label: 'Laisser passer, prudent', effect: { temps: -8, energie: 2 }, result: 'Trop risqué. Tu attends la suivante, frustré.' },
    ],
  },
  {
    id: 'musicien_metro',
    sprite: 'barman',
    decor: 'arret_bus',
    prop: 'piece',
    title: 'Le musicien du wagon',
    text: 'Un accordéoniste s’installe et entame le même air que d’habitude, juste devant toi.',
    choices: [
      { label: 'Donner une pièce', effect: { temps: -2, argent: -1, moral: 6 }, result: 'Un sourire d’artiste. Le voyage est moins gris.' },
      { label: 'Fixer le vide', effect: { temps: -2, moral: -3 }, result: 'Tu fais celui qui n’entend rien. L’air te trotte dans la tête tout le trajet.' },
    ],
  },
  {
    id: 'greve',
    sprite: 'collegue',
    decor: 'arret_bus',
    prop: 'journal',
    title: 'Le préavis de grève',
    text: 'Un panneau annonce un service réduit. Un seul train sur trois, et tous bondés.',
    choices: [
      { label: 'Tenter le coup quand même', effect: { temps: -7, energie: -5 }, result: 'Tu finis par en attraper un. Compressé, mais en mouvement.' },
      { label: 'Commander un VTC', effect: { temps: -4, argent: -12 }, result: 'Une voiture en cinq minutes. Le portefeuille trinque, le temps est sauvé.' },
    ],
  },
  {
    id: 'portillon',
    sprite: 'papa',
    decor: 'arret_bus',
    prop: 'ticket',
    title: 'Le portillon bloqué',
    text: 'Ton titre de transport est refusé par le portillon, qui se referme net sur ton sac.',
    choices: [
      { label: 'Repasser ton ticket', effect: { temps: -5 }, result: 'Au deuxième passage, le portillon consent à s’ouvrir.' },
      { label: 'Appeler un agent', effect: { temps: -9, moral: 2 }, result: 'Un agent débloque le tout et t’ouvre un accès. Lent mais sûr.' },
    ],
  },
  {
    id: 'vtc_annule',
    sprite: 'vigile',
    decor: 'arret_bus',
    prop: 'carte',
    title: 'Le VTC qui annule',
    text: 'Ton chauffeur annule à la dernière seconde. L’appli en propose un autre... à quelques rues de là.',
    choices: [
      { label: 'Marcher à sa rencontre', effect: { temps: -6, energie: -4 }, result: 'Tu coupes au plus court vers le nouveau point de prise en charge.' },
      { label: 'Recommander, plus cher', effect: { temps: -3, argent: -8 }, result: 'Tu paies le tarif de pointe pour une voiture immédiate.' },
    ],
  },
  {
    id: 'escalator_metro',
    sprite: 'mamie',
    decor: 'arret_bus',
    prop: 'horloge',
    title: "L'escalator hors service",
    text: 'L’escalator de la station est figé, transformé en raides escaliers, et la foule s’y agglutine.',
    choices: [
      { label: 'Grimper à pied', effect: { temps: -4, energie: -3 }, result: 'Tu montes deux à deux, essoufflé mais rapide.' },
      { label: 'Chercher l’ascenseur', effect: { temps: -9, energie: -1 }, result: 'Tu fais le tour pour l’ascenseur. Reposant, mais à l’autre bout.' },
    ],
  },
]

// Source d'argent : garantie dans la première zone par le moteur.
export const DISTRIBUTEUR: GameEvent = {
  id: 'distributeur',
  sprite: 'papa',
  decor: 'atm',
  prop: 'carte',
  money: true,
  title: 'Le distributeur',
  text: 'Un distributeur clignote au coin de la rue. La mission va coûter : autant prévoir.',
  choices: [
    { label: 'Retirer du liquide', effect: { temps: -6, argent: 30 }, result: 'Trente euros en poche. La mission redevient confortable.' },
    { label: 'Tenter sans retirer', effect: { temps: -1, moral: -3 }, result: 'Tu fais avec le peu que tu as. Pari audacieux.' },
  ],
}
